version: '3'

services: 
  database_os:
    image: mysql:5.7
    volumes:
      - dbstorage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: roopass
      MYSQL_USER: username
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: database

  wordpress_os:
    image: wordpress:5.1.1-php7.3-apache
    restart: always
    depends_on:
      - database_os
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: database_os
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: userpass
      WORDPRESS_DB_NAME: database
    volumes:
      - wpstorage:/var/www/html

volumes:
   dbstorage:
   wpstorage:

